In [1]:
import numpy as np

In [2]:
list1 = [2,3,4,6,7,9]
np.array(list1)

array([2, 3, 4, 6, 7, 9])

In [7]:
list_of_list = [[1,4,5,6,1],[23,5,6,2,5],[2,5,7,2,3]]

two_2d = np.array(list_of_list)
two_2d

array([[ 1,  4,  5,  6,  1],
       [23,  5,  6,  2,  5],
       [ 2,  5,  7,  2,  3]])

In [11]:
np.array(two_2d)

array([[ 1,  4,  5,  6,  1],
       [23,  5,  6,  2,  5],
       [ 2,  5,  7,  2,  3]])

In [6]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.eye(8,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [24]:
np.linspace(3,90,6)

array([ 3. , 20.4, 37.8, 55.2, 72.6, 90. ])

In [30]:
mant =np.linspace(2,8)
mant

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [32]:
np.random.randint(1,10)

4

In [36]:
np.random.rand(2,10)

array([[0.76056705, 0.01858572, 0.27347508, 0.46524377, 0.5221687 ,
        0.54278713, 0.03429155, 0.40591847, 0.00419725, 0.53771395],
       [0.02772294, 0.61886039, 0.43486204, 0.2007836 , 0.91848465,
        0.36125503, 0.08251944, 0.49186197, 0.48291163, 0.64298309]])

In [39]:
anrr =np.random.randn(3,4)
anrr

array([[-1.41756473,  0.12533857,  0.989283  ,  0.35888025],
       [ 0.38917587, -0.84274408, -0.90101467, -0.22746454],
       [ 0.9245659 , -0.61554431,  0.0297359 ,  0.97299832]])

In [41]:
np.random.randint(2,100)

8

In [ ]:
np.random.

In [47]:
sample_array = np.arange(40)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [49]:
sample_array.reshape(4,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [51]:

rand_int = np.random.randint(2,5,10)
rand_int

array([2, 3, 3, 4, 2, 2, 2, 4, 2, 3])

In [55]:
rand_int.reshape(2,5)

array([[2, 3, 3, 4, 2],
       [2, 2, 4, 2, 3]])